version: '2'

services:
  jde-microserver:
    image: 92455890/jdeatina-microserver:1.0.0
    environment:
      JDE_MICROSERVER_IP: ${JDE_MICROSERVER_IP}
      JDE_MICROSERVER_PORT: ${JDE_MICROSERVER_PORT}  
      JDE_MICROSERVER_CODE: ${JDE_MICROSERVER_CODE}
      JDE_MICROSERVER_JDE_LIB_WRAPPED: ${JDE_MICROSERVER_JDE_LIB_WRAPPED}
      JDE_MICROSERVER_STD_WEB_SERVICE: ${JDE_MICROSERVER_STD_WEB_SERVICE}
      JDE_MICROSERVER_JDE_ATINA_SERVER: ${JDE_MICROSERVER_JDE_ATINA_SERVER}
      JDE_MICROSERVER_SECRET_KEY: ${JDE_MICROSERVER_SECRET_KEY}
      JDE_MICROSERVER_TOKEN_EXPIRATION: ${JDE_MICROSERVER_TOKEN_EXPIRATION}
      JDE_MICROSERVER_ENTERPRISE_SERVER_NAME: ${JDE_MICROSERVER_ENTERPRISE_SERVER_NAME}
      JDE_MICROSERVER_ENTERPRISE_SERVER_IP: ${JDE_MICROSERVER_ENTERPRISE_SERVER_IP}
      JDE_MICROSERVER_ENTERPRISE_DB_NAME: ${JDE_MICROSERVER_ENTERPRISE_DB_NAME}
      JDE_MICROSERVER_ENTERPRISE_DB_IP: ${JDE_MICROSERVER_ENTERPRISE_DB_IP}
      ATINA_REPOSITORY_PROTOCOL: ${ATINA_REPOSITORY_PROTOCOL}
      ATINA_REPOSITORY_URL: ${ATINA_REPOSITORY_URL}
      CUSTOMER_REPOSITORY_PROTOCOL: ${CUSTOMER_REPOSITORY_PROTOCOL}
      CUSTOMER_REPOSITORY_URL: ${CUSTOMER_REPOSITORY_URL}
    container_name: jdeatina-microserver
    ports:
     - "${JDE_MICROSERVER_PORT}:${JDE_MICROSERVER_PORT}"
    volumes:
     - /tmp/jde:/tmp/jde
    user: root
    restart: always 
