version: '2'

services:
  jde-microserver:
    build: docker_jdemicroserver
    image: 92455890/jdeatina-microserver:1.0.0
    environment:
      JDE_MICROSERVER_IP: ${JDE_MICROSERVER_IP}
      JDE_MICROSERVER_PORT: ${JDE_MICROSERVER_PORT}  
      JDE_MICROSERVER_CODE: ${JDE_MICROSERVER_CODE}
      JDE_MICROSERVER_JDE_LIB_WRAPPED: ${JDE_MICROSERVER_JDE_LIB_WRAPPED}
      JDE_MICROSERVER_STD_WEB_SERVICE: ${JDE_MICROSERVER_STD_WEB_SERVICE}
      JDE_MICROSERVER_SECRET_KEY: ${JDE_MICROSERVER_SECRET_KEY}
      JDE_MICROSERVER_TOKEN_EXPIRATION: ${JDE_MICROSERVER_TOKEN_EXPIRATION}
      JDE_MICROSERVER_ENTERPRISE_SERVER_NAME: ${JDE_MICROSERVER_ENTERPRISE_SERVER_NAME}
      JDE_MICROSERVER_ENTERPRISE_SERVER_IP: ${JDE_MICROSERVER_ENTERPRISE_SERVER_IP}
      JDE_MICROSERVER_ENTERPRISE_DB_NAME: ${JDE_MICROSERVER_ENTERPRISE_DB_NAME}
      JDE_MICROSERVER_ENTERPRISE_DB_IP: ${JDE_MICROSERVER_ENTERPRISE_DB_IP}
      REPOSITORY_PROTOCOL: ${REPOSITORY_PROTOCOL}
      REPOSITORY_URL: ${REPOSITORY_URL}
    container_name: jdeatina-microserver
    depends_on: 
     - ngrok-microserver
    ports:
     - "${JDE_MICROSERVER_PORT}:${JDE_MICROSERVER_PORT}"
    volumes:
     - /tmp/jde/config:/tmp/jde/config
     - /tmp/jde/lib:/tmp/jde/lib
    user: root
    networks:
      atinanet:
        ipv4_address: 172.28.0.7
    restart: always 

  ngrok-microserver:
    build: docker_jdemicroserver_ngrok
    image: 92455890/ngrok-microserver:1.0.0
    environment:
      NGROK_MICROSERVER_TOKEN: ${NGROK_MICROSERVER_TOKEN}
      NGROK_MICROSERVER_HOST: ${NGROK_MICROSERVER_HOST}
      NGROK_MICROSERVER_PORT: ${NGROK_MICROSERVER_PORT}
    ports:
      - "4040:4040"
    container_name: ngrok-microserver
    networks:
      atinanet:
        ipv4_address: 172.28.0.6
    
networks:
  atinanet:
    driver: bridge
    ipam:
     config:
       - subnet: 172.28.0.0/16
         gateway: 172.28.0.1