version: '2'

services:
    
  jde-microserver:
    build: docker_jdemicro
    image: 92455890/jdeatina-microserver:1.0.0
    environment:
      JDE_MICROSERVER_IP: ${JDE_MICROSERVER_IP}
      JDE_MICROSERVER_PORT: ${JDE_MICROSERVER_PORT}  
      JDE_MICROSERVER_CODE: ${JDE_MICROSERVER_CODE}
      JDE_MICROSERVER_JDE_LIB_WRAPPED: ${JDE_MICROSERVER_JDE_LIB_WRAPPED}
      JDE_MICROSERVER_STD_WEB_SERVICE: ${JDE_MICROSERVER_STD_WEB_SERVICE}
      JDE_MICROSERVER_SECRET_KEY: ${JDE_MICROSERVER_SECRET_KEY}
      JDE_MICROSERVER_TOKEN_EXPIRATION: ${JDE_MICROSERVER_TOKEN_EXPIRATION}
      REPOSITORY_PROTOCOL: ${REPOSITORY_PROTOCOL}
      REPOSITORY_URL: ${REPOSITORY_URL}
    container_name: jdeatina-microserver
    depends_on: 
     - ngrok-microserver
    ports:
     - "${JDE_MICROSERVER_PORT}:${JDE_MICROSERVER_PORT}"
    volumes:
     - /tmp/jde/config:/tmp/jde/config
     - /tmp/jde/lib:/tmp/jde/lib
    user: root
    networks:
      atinanet:
        ipv4_address: 172.26.0.3
    restart: always 

  ngrok-microserver:
    build: docker_ngrok
    image: 92455890/ngrok-microserver:1.0.0
    environment:
      NGROK_NGROK_TOKEN: ${NGROK_NGROK_TOKEN}
      NGROK_MULE_SERVER_HOST: ${NGROK_MULE_SERVER_HOST}
      NGROK_MULE_SERVER_PORT: ${NGROK_MULE_SERVER_PORT}
    ports:
      - "4040:4040"
    container_name: ngrok-microserver
    networks:
      atinanet:
        ipv4_address: 172.26.0.2
    
networks:
  atinanet:
    driver: bridge
    ipam:
     config:
       - subnet: 172.26.0.0/16
         gateway: 172.26.0.1
