version: '2'

services:
    
  jde-microserver:
    build: docker_jdemicro
    image: soporteacqua/jdeatina-server:1.0.0
    environment:
      JDE_MICROSERVER_IP: ${JDE_MICROSERVER_IP}
      JDE_MICROSERVER_PORT: ${JDE_MICROSERVER_PORT}  
      JDE_MICROSERVER_CODE: ${JDE_MICROSERVER_CODE}
      JDE_MICROSERVER_JDE_LIB_WRAPPED: ${JDE_MICROSERVER_JDE_LIB_WRAPPED}
      JDE_MICROSERVER_STD_WEB_SERVICE: ${JDE_MICROSERVER_STD_WEB_SERVICE}
      JDE_MICROSERVER_SECRET_KEY: ${JDE_MICROSERVER_SECRET_KEY}
      JDE_MICROSERVER_TOKEN_EXPIRATION: ${JDE_MICROSERVER_TOKEN_EXPIRATION}
    container_name: jdeatina-server
    ports:
     - "${JDE_MICROSERVER_PORT}:${JDE_MICROSERVER_PORT}"
    volumes:
     - /tmp/jde/config:/tmp/jde/config
     - /tmp/jde/lib:/tmp/jde/lib
    user: root
    networks:
      atinanet:
        ipv4_address: 172.26.0.2
    restart: always 
     
    
networks:
  atinanet:
    driver: bridge
    ipam:
     config:
       - subnet: 172.26.0.0/16
         gateway: 172.26.0.1
