version: '3.6'

services:

  vault:
    build: vault
    image: 92455890/jdeatina-vault:1.0.0
    container_name: jdeatina-microserver-vault
    ports:
      - 8200:8200
      - 8201:8201
    restart: always
    cap_add:
      - IPC_LOCK
