version: '3.6'

services:

  vault:
    build: vault
    image: 92455890/jdeatina-vault:1.0.0
    container_name: jdeatina-microserver-vault
    environment:
      VAULT_VERSION: '1.3.3'
      VAULT_LOCAL_CONFIG: '{"backend": {"file": {"path": "vault/data"}},"listener": {"tcp": {"address": "0.0.0.0:8200","tls_disable": 1}},"ui": true}'
    ports:
      - 8200:8200
    restart: always
    cap_add:
      - IPC_LOCK
