version: '2'

services:
  mule-server:
    build: docker_mulesoft
    image: 92455890/mule-server:1.0.0
    environment:
      jdeAtinaVersion: ${jdeAtinaVersion}
      JDE_CONNECTOR_USER: ${JDE_CONNECTOR_USER}
      JDE_CONNECTOR_PASSWORD: ${JDE_CONNECTOR_PASSWORD}
      JDE_CONNECTOR_ENVIRONMENT: ${JDE_CONNECTOR_ENVIRONMENT}
      JDE_CONNECTOR_ROLE: ${JDE_CONNECTOR_ROLE}
      JDE_CONNECTOR_MICROSERVER_NAME: ${JDE_CONNECTOR_MICROSERVER_NAME}
      JDE_CONNECTOR_MICROSERVER_PORT: ${JDE_CONNECTOR_MICROSERVER_PORT} 
      dragon_shopify_smtp_host: ${dragon_shopify_smtp_host}
      dragon_shopify_smtp_port: ${dragon_shopify_smtp_port}
      dragon_shopify_smtp_user: ${dragon_shopify_smtp_user}
      dragon_shopify_smtp_pass: ${dragon_shopify_smtp_pass}
      dragon_shopify_smtp_email_from: ${dragon_shopify_smtp_email_from}
      dragon_shopify_smtp_email_to: ${dragon_shopify_smtp_email_to} 
      dragon_shopify_smtp_email_errorSubject: ${dragon_shopify_smtp_email_errorSubject}
      dragon_shopify_smtp_email_msgSubject: ${dragon_shopify_smtp_email_msgSubject}
      metrics_graphite_enable: ${metrics_graphite_enable}
      metrics_graphite_server: ${metrics_graphite_server}
      metrics_graphite_port: ${metrics_graphite_port}
      REPOSITORY_PROTOCOL: ${REPOSITORY_PROTOCOL}
      REPOSITORY_URL: ${REPOSITORY_URL}
    container_name: mule-server
    depends_on: 
     - ngrok-server
    ports:
     - "8083:8083"
     - "8084:8084"
     - "8088:8081"
     - "8161:8161"
    volumes:
     - /tmp/docker/mule-server/logs:/opt/mule/mule-standalone-390/logs
     - /tmp/docker/mule-server/apps:/opt/mule/mule-standalone-390/apps
    links:
     - ngrok-server:ngrok-server
    user: root
    networks:
      atinacloud:
        ipv4_address: 172.28.0.3

  ngrok-server:
    build: docker_mulesoft_ngrok
    image: 92455890/ngrok-server:1.0.0
    environment:
      NGROK_MULE_SERVER_TOKEN: ${NGROK_MULE_SERVER_TOKEN}
      NGROK_MULE_SERVER_HOST: ${NGROK_MULE_SERVER_HOST}
      NGROK_MULE_SERVER_PORT: ${NGROK_MULE_SERVER_PORT}
    ports:
      - "4041:4040"
    container_name: ngrok-server
    networks:
      atinacloud:
        ipv4_address: 172.28.0.2    
    
networks:
  atinacloud:
    driver: bridge
    ipam:
     config:
       - subnet: 172.28.0.0/16
         gateway: 172.28.0.1
